
[[redirects]]
  from = "/api/*"
  to = "https://workoutbuddy-whov.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
